import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Generates src/version.ts from package.json — package.json is the single
 * authoritative version source; this file is regenerated on every build
 * (see the "prebuild" script) and must not be edited by hand.
 */
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'))

if (typeof pkg.version !== 'string' || !/^\d+\.\d+\.\d+/.test(pkg.version)) {
  throw new Error(`package.json version is missing or malformed: ${JSON.stringify(pkg.version)}`)
}

mkdirSync(resolve(root, 'src'), { recursive: true })
writeFileSync(
  resolve(root, 'src/version.ts'),
  `// GENERATED by scripts/generate-version.mjs from package.json — do not edit.\n` +
    `export const APP_VERSION = '${pkg.version}'\n`
)
console.log(`✓ version.ts generated (v${pkg.version})`)
